### ISSUE TITLE
Using cargo-packaging with an older cargo/rust version leads to unresolvable

### ISSUE THREAD

**Issue by kastl-ars** [Firstyear/cargo-packaging#12] opened 2024-10-16 06:15 UTC
Hi all,

after @darix has succeeded in packaging [Vector](https://github.com/vectordotdev/vector), I wanted to check if I can get this to build on Leap 15.6. But this fails:

```
conflict for providers of cargo needed by cargo-packaging, (provider cargo obsoletes cargo1.79)
```

The reason is that the spec explicitly requests rust1.79 and cargo1.79, as the latest released Vector version does not yet build with rust 1.80 or higher.

Is this something  we can fix in the cargo-packaging RPM? Or do we need to remove the `Obsoletes` in the cargo package to solve this?

It seems to work on Tumbleweed, so this might already be solved, but not included in 15.6. Not sure if we have a chance to fix this for 15.6?

Kind Regards,
Johannes

**Comment by Firstyear** [comment] 2024-10-16 06:17
Set "BuildRequires cargo1.79" in your .spec and it works.

**Comment by kastl-ars** [comment] 2024-10-16 06:33
> Set "BuildRequires cargo1.79" in your .spec and it works.

That is what darix used. Here is my branched package:

https://build.opensuse.org/projects/home:ojkastl_buildservice:vector/packages/vector/files/vector.spec?expand=1

Lines 33 and 36

```
BuildRequires:  cargo-packaging
BuildRequires:  cargo1.79
BuildRequires:  gcc-c++
BuildRequires:  pkgconfig
BuildRequires:  rust1.79
```

**Comment by Firstyear** [comment] 2024-10-16 06:35
I think we already fixed this in SLE, so I wonder if it's just a delay in the package landing in 15.6?

**Comment by kastl-ars** [comment] 2024-10-16 06:37
> I think we already fixed this in SLE, so I wonder if it's just a delay in the package landing in 15.6?

I am building against SLE15-SP6 in my project. So if this is fixed in SLE, it is not yet working on OBS.

```
  <repository name="15.6">
    <path project="SUSE:SLE-15-SP6:GA" repository="standard"/>
    <arch>x86_64</arch>
  </repository>
```

**Comment by Firstyear** [comment] 2024-10-16 06:38
Was fixed 3 months ago: https://build.opensuse.org/package/revisions/devel:languages:rust/cargo-packaging

So I have no idea what the issue is otherwise. Sounds like an IBS/OBS issue, so I'm powerless to assist.

**Comment by kastl-ars** [comment] 2024-10-16 06:43
Thanks for checking, William! I have branched the cargo-packaging package to my project and will see if it works.

I guess the the package was submitted to SLE/Leap and not only to Tumbleweed/Factory?

**Comment by kastl-ars** [comment] 2024-10-16 06:45
> Thanks for checking, William! I have branched the cargo-packaging package to my project and will see if it works.

Using the branched cargo-packaging package solves the `unresolvable`. So the only issue is, why this is not in SLE.

I'll try to find out.

**Comment by Firstyear** [comment] 2024-10-17 00:09
Thanks. IBS/OBS are "black boxes" to me, so once I submit something it's kind of a mystery how it appears anywhere else.

**Comment by Firstyear** [comment] 2024-10-17 00:10
Either way, closing as this is already fixed from our view.

**Closed as completed by Firstyear** 2024-10-17 00:10 UTC
